# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualization.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1077, 693)
        Form.setStyleSheet("")
        self.label_img_show = QtWidgets.QLabel(Form)
        self.label_img_show.setGeometry(QtCore.QRect(10, 9, 621, 481))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(30)
        font.setItalic(False)
        self.label_img_show.setFont(font)
        self.label_img_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_img_show.setText("")
        self.label_img_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_show.setObjectName("label_img_show")
        self.te_screen_display = QtWidgets.QTextBrowser(Form)
        self.te_screen_display.setGeometry(QtCore.QRect(650, 10, 361, 211))
        self.te_screen_display.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.te_screen_display.setObjectName("te_screen_display")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(10, 510, 411, 131))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.widget.setFont(font)
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setAutoFillBackground(False)
        self.widget.setObjectName("widget")
        self.load_class = QtWidgets.QPushButton(self.widget)
        self.load_class.setGeometry(QtCore.QRect(20, 80, 91, 31))
        self.load_class.setObjectName("load_class")
        self.load_model_path = QtWidgets.QLineEdit(self.widget)
        self.load_model_path.setGeometry(QtCore.QRect(130, 10, 271, 31))
        self.load_model_path.setObjectName("load_model_path")
        self.load_model = QtWidgets.QPushButton(self.widget)
        self.load_model.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.load_model.setObjectName("load_model")
        self.load_class_path = QtWidgets.QLineEdit(self.widget)
        self.load_class_path.setGeometry(QtCore.QRect(130, 80, 271, 31))
        self.load_class_path.setObjectName("load_class_path")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setEnabled(True)
        self.widget_2.setGeometry(QtCore.QRect(650, 240, 361, 250))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.widget_2.setPalette(palette)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.btn_batch_img = QtWidgets.QPushButton(self.widget_2)
        self.btn_batch_img.setGeometry(QtCore.QRect(20, 70, 91, 31))
        self.btn_batch_img.setObjectName("btn_batch_img")
        self.batch_img_path = QtWidgets.QLineEdit(self.widget_2)
        self.batch_img_path.setGeometry(QtCore.QRect(130, 70, 221, 31))
        self.batch_img_path.setObjectName("batch_img_path")
        self.btn_img = QtWidgets.QPushButton(self.widget_2)
        self.btn_img.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.btn_img.setObjectName("btn_img")
        self.img_path = QtWidgets.QLineEdit(self.widget_2)
        self.img_path.setGeometry(QtCore.QRect(130, 10, 221, 31))
        self.img_path.setObjectName("img_path")
        self.recognize_img = QtWidgets.QPushButton(self.widget_2)
        self.recognize_img.setGeometry(QtCore.QRect(20, 130, 91, 31))
        self.recognize_img.setObjectName("recognize_img")
        self.OpenDirBtn = QtWidgets.QPushButton(self.widget_2)
        self.OpenDirBtn.setGeometry(QtCore.QRect(20, 190, 91, 31))
        self.OpenDirBtn.setObjectName("OpenDirBtn")
        self.PreImBtn = QtWidgets.QPushButton(self.widget_2)
        self.PreImBtn.setGeometry(QtCore.QRect(130, 190, 75, 31))
        self.PreImBtn.setObjectName("PreImBtn")
        self.NextImBtn = QtWidgets.QPushButton(self.widget_2)
        self.NextImBtn.setGeometry(QtCore.QRect(240, 190, 75, 31))
        self.NextImBtn.setObjectName("NextImBtn")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setEnabled(True)
        self.widget_3.setGeometry(QtCore.QRect(650, 510, 361, 100))
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.v_det_btn = QtWidgets.QPushButton(self.widget_3)
        self.v_det_btn.setGeometry(QtCore.QRect(20, 60, 91, 31))
        self.v_det_btn.setObjectName("v_det_btn")
        self.btn_v = QtWidgets.QPushButton(self.widget_3)
        self.btn_v.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.btn_v.setObjectName("btn_v")
        self.video_path = QtWidgets.QLineEdit(self.widget_3)
        self.video_path.setGeometry(QtCore.QRect(130, 10, 221, 31))
        self.video_path.setObjectName("video_path")
        self.pb_quit = QtWidgets.QPushButton(Form)
        self.pb_quit.setGeometry(QtCore.QRect(930, 650, 75, 31))
        self.pb_quit.setObjectName("pb_quit")
        self.refresh = QtWidgets.QPushButton(Form)
        self.refresh.setGeometry(QtCore.QRect(480, 520, 75, 31))
        self.refresh.setObjectName("refresh")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.load_class.setText(_translate("Form", "加载类别"))
        self.load_model.setText(_translate("Form", "加载模型"))
        self.btn_batch_img.setText(_translate("Form", "批量图片"))
        self.btn_img.setText(_translate("Form", "加载图片"))
        self.recognize_img.setText(_translate("Form", "图像识别"))
        self.OpenDirBtn.setText(_translate("Form", "打开生成目录"))
        self.PreImBtn.setText(_translate("Form", "上一张"))
        self.NextImBtn.setText(_translate("Form", "下一张"))
        self.v_det_btn.setText(_translate("Form", "视频识别"))
        self.btn_v.setText(_translate("Form", "加载视频"))
        self.pb_quit.setText(_translate("Form", "退出"))
        self.refresh.setText(_translate("Form", "刷新"))

